version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=p
      - DB_NAME=FlightData
    depends_on:
      - db
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: mysql:8.0
    container_name: wpi509-db
    environment:
      MYSQL_ROOT_PASSWORD: p
      MYSQL_DATABASE: FlightData
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  