version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
    # 1. Keep this for the "host.docker.internal" connection
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # 2. Add these variables so your code knows where to look
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3333
      - DB_USER=root
      - DB_PASS=p
      - DB_NAME=FlightData
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /bin/sh -c "while sleep 1000; do :; done"